In [159]:
def insertion_sort(a) :
    n = len(a)
    # i = 1
    # sorted a[0..i-1]
    for i in range(1, n) :
        # insert i in the right position
        j = i - 1
        el = a[i]
        while el < a[j] and j > 0 :
            a[j + 1] = a[j]
            j = j - 1
        # el >= a[j] or j == 0
        if el < a[j] : # j == 0
            a[1] = a[0]
            a[0] = el
        else : # el >= a[j] 
            a[j + 1] = el
    return a

In [125]:
a = [1, 10, 3, 5, -3, 7, 9, 0]
print(insertion_sort(a))

[-3, 0, 1, 3, 5, 7, 9, 10]


In [160]:
import numpy as np
randarr = np.random.randint(1, 26, 10)

In [161]:
randarr

array([ 8, 22, 13,  4, 23, 11,  4,  9, 12,  8])

In [164]:

randarr = np.random.randint(1, 100, 4)
print(randarr)
print(insertion_sort(randarr))

[91 36 41 58]
[36 41 58 91]


In [166]:
insertion_sort([2, 1, 3, 10, -100])

[-100, 1, 2, 3, 10]